spring:
  datasource:
    url: ${DB_JDBC_URL:jdbc:mariadb://localhost:3306/test}
    username: ${DB_USERNAME:readalyse}
    password: ${DB_PASSWORD:readalyse}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    table: flyway_schema_history
    default-schema: test
    enabled: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, prometeus
      base-path: /status
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
    prometheus:
      enabled: true
  server:
    port: 8090

server:
  servlet:
    context-path: /api

logging:
  level:
    root: info
  file:
      informationExtraction: C:/Users/Dela/log/InformationExtraction.log
      readabilityScores: C:/Users/Dela/log/ReadabilityScoresAnalysis.log


projectGutenberg:
  url: ${PROJECT_GUTENBERG_URL:https://gutenberg.org/cache/epub/feeds/rdf-files.tar.bz2}
  downloadBaseDirectory: ${DOWNLOAD_BASE_DIRECTORY:C:/Users/Dela/background-workers/all-time-data}
  downloadedFilesPath: ${DOWNLOADED_FILES_PATH:C:/Users/Dela/background-workers/all-time-data/rdf-files.tar.bz2}







