openapi: 3.0.0
info:
  title: Readalyse API
  description: Readalyse API
  version: 0.0.1
servers:
  - url: http://localhost:8080/api
    description: Generated server url
paths:
  /books:
    $ref: './paths/books.yaml'
  /books/{bookId}:
    $ref: './paths/book.yaml'
  /agents:
    $ref: './paths/agents.yaml'
  /discover/recommended:
    $ref: './paths/discover/recommended.yaml'
  /discover/new-additions:
    $ref: './paths/discover/new-additions.yaml'
  /discover/trending:
    $ref: './paths/discover/trending.yaml'
  /discover/highest-rated:
    $ref: './paths/discover/highest-rated.yaml'
  /library/currently-reading:
    $ref: './paths/user/currently-reading.yaml'
  /library/want-to-read:
    $ref: './paths/user/want-to-read.yaml'
  /library/favorites:
    $ref: './paths/user/favorites.yaml'
  /library/finished-reading:
    $ref: './paths/user/finished.yaml'
  /library/status/{bookId}:
    $ref: './paths/user/update-status.yaml'
  /library/favorites/{bookId}/switch:
    $ref: './paths/user/add-remove-favorite.yaml'
  /auth/register:
    $ref: './paths/authentication/register.yaml'
  /auth/login:
    $ref: './paths/authentication/login.yaml'
  /review:
    $ref: './paths/review/reviews.yaml'
  /review/{reviewId}:
    $ref: './paths/review/review.yaml'
  /review/book/{bookId}:
    $ref: './paths/review/reviews-by-book.yaml'
  /review/user/{bookId}:
    $ref: './paths/review/review-of-user.yaml'
components:
  schemas:
    BookList:
      $ref: './components/schemas/Book/BookList.yaml'
    Book:
      $ref: './components/schemas/Book/Book.yaml'
    AgentType:
      $ref: './components/schemas/AgentType/AgentType.yaml'
    AgentList:
      $ref: './components/schemas/Agent/AgentList.yaml'
    Agent:
      $ref: './components/schemas/Agent/Agent.yaml'
    BookshelfList:
      $ref: './components/schemas/Bookshelf/BookshelfList.yaml'
    Bookshelf:
      $ref: './components/schemas/Bookshelf/Bookshelf.yaml'
    LanguageList:
      $ref: './components/schemas/Language/LanguageList.yaml'
    Language:
      $ref: './components/schemas/Language/Language.yaml'
    Person:
      $ref: './components/schemas/Person/Person.yaml'
    ResourceList:
      $ref: './components/schemas/Resource/ResourceList.yaml'
    Resource:
      $ref: './components/schemas/Resource/Resource.yaml'
    SubjectList:
      $ref: './components/schemas/Subject/SubjectList.yaml'
    Subject:
      $ref: './components/schemas/Subject/Subject.yaml'
    Pagination:
      $ref: './components/schemas/Pagination.yaml'
    ReviewList:
      $ref: './components/schemas/Review/ReviewList.yaml'
    Review:
      $ref: './components/schemas/Review/Review.yaml'
    User:
      $ref: './components/schemas/User.yaml'
    RoleEnum:
      $ref: './components/schemas/RoleEnum.yaml'
    StatusEnum:
      $ref: './components/schemas/StatusEnum.yaml'
    ReadingStatus:
      $ref: './components/schemas/ReadingStatus/ReadingStatus.yaml'
    ReadabilityScores:
      $ref: './components/schemas/Book/ReadabilityScores.yaml'