openapi: 3.0.0
info:
  title: Readalyse API
  description: Readalyse API
  version: 0.0.1
servers:
  - url: http://localhost:8080/api
    description: Generated server url
paths:
  /books:
    $ref: './paths/books.yaml'
  /agents:
    $ref: './paths/agents.yaml'
  /discover/recommended:
    $ref: './paths/recommended.yaml'
components:
  schemas:
    AgentType:
      $ref: './components/schemas/AgentType/AgentType.yaml'
    AgentList:
      $ref: './components/schemas/Agent/AgentList.yaml'
    Agent:
      $ref: './components/schemas/Agent/Agent.yaml'
    BookshelfList:
      $ref: './components/schemas/Bookshelf/BookshelfList.yaml'
    Bookshelf:
      $ref: './components/schemas/Bookshelf/Bookshelf.yaml'
    LanguageList:
      $ref: './components/schemas/Language/LanguageList.yaml'
    Language:
      $ref: './components/schemas/Language/Language.yaml'
    Person:
      $ref: './components/schemas/Person/Person.yaml'
    ResourceList:
      $ref: './components/schemas/Resource/ResourceList.yaml'
    Resource:
      $ref: './components/schemas/Resource/Resource.yaml'
    SubjectList:
      $ref: './components/schemas/Subject/SubjectList.yaml'
    Subject:
      $ref: './components/schemas/Subject/Subject.yaml'
    Book:
      $ref: './components/schemas/Book/Book.yaml'
    BookList:
      $ref: './components/schemas/Book/BookList.yaml'
    Pagination:
      $ref: './components/schemas/Pagination.yaml'