/**
 * Readalyse API
 * Readalyse API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgentType } from './agentType';
import { Person } from './person';


export interface Agent { 
    id?: number;
    person?: Person;
    agentType?: AgentType;
}

