/**
 * Readalyse API
 * Readalyse API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Agent } from './agent';
import { Language } from './language';
import { ReadabilityScores } from './readabilityScores';
import { Bookshelf } from './bookshelf';
import { Resource } from './resource';
import { Subject } from './subject';


/**
 * Book model.
 */
export interface Book { 
    id?: number;
    title?: string;
    description?: string;
    downloads?: string;
    readabilityScores?: ReadabilityScores;
    agents?: Array<Agent>;
    bookshelves?: Array<Bookshelf>;
    languages?: Array<Language>;
    resources?: Array<Resource>;
    subjects?: Array<Subject>;
}

